export type BrandFull = {
  name: string;
  logo: string;
  category: string;
  tagline: string;
  about: string;
  website: string;
};

const B = "https://www.pvlumens.com";

export const BRAND_DATA: BrandFull[] = [

  // ─── Network Infrastructure ───────────────────────────────────────────
  {
    name: "Commscope",
    logo: `/commscope.webp`,
    category: "Network Infrastructure",
    tagline: "Global Network Infrastructure Provider",
    about: "CommScope is a major global provider of network infrastructure — connectivity and cabling solutions, along with broadband and wireless network technology used by network operators and enterprises worldwide. It's one of the most established names in physical network infrastructure. Publicly traded (NASDAQ: COMM), headquartered in Claremont, North Carolina, USA.",
    website: "https://www.commscope.com",
  },
  {
    name: "Vertiv",
    logo: `${B}/images/clientIcon/Vertiv-Logo.svg`,
    category: "Network Infrastructure",
    tagline: "Critical Digital Infrastructure",
    about: "Vertiv, a publicly traded company (NYSE: VRT) headquartered in Columbus, Ohio, designs the critical infrastructure that keeps data centres running — from power management to advanced cooling systems. Operating in over 130 countries, Vertiv serves everything from small server rooms to hyperscale data centres, with a singular focus on environments where uptime is non-negotiable.",
    website: "https://www.vertiv.com",
  },
  {
    name: "Netrack",
    logo: `${B}/images/clientIcon/logo.png`,
    category: "Network Infrastructure",
    tagline: "Server Racks & Enclosures",
    about: "Netrack manufactures server racks and data centre enclosures engineered for durability and compatibility with international mounting standards, giving installers flexibility as they build out network infrastructure. Their products are designed to meet the evolving demands of modern enterprise and colocation data centre environments.",
    website: "https://www.netrack.in",
  },
  {
    name: "Panduit",
    logo: `${B}/images/clientIcon/Panduit-logo01.jpg`,
    category: "Network Infrastructure",
    tagline: "Physical Network Infrastructure",
    about: "Panduit, a privately held, family-owned company headquartered in Tinley Park, Illinois, is a global leader in physical network infrastructure and connectivity solutions. For nearly 70 years, Panduit has engineered structured cabling, racks, and cable management systems trusted by data centres and enterprises across more than 100 countries.",
    website: "https://www.panduit.com",
  },
  {
    name: "Atlona",
    logo: `${B}/images/clientIcon/Atlona%20Logo%20-%20160px%20x%2050px.png`,
    category: "Network Infrastructure",
    tagline: "AV Distribution & Collaboration",
    about: "Atlona, a Panduit company, is a leading manufacturer of AV distribution, AV over IP, collaboration, and control solutions. Atlona's core brand vision centers on improving technology for the sharing of ideas through innovative AV products used across commercial and educational applications — backed by an award-winning 10-year warranty on all products.",
    website: "https://atlona.com",
  },
  {
    name: "Fluke Networks",
    logo: `${B}/images/clientIcon/FNet_White_Blue_Box_RGB.JPG`,
    category: "Network Infrastructure",
    tagline: "Network Certification Tools",
    about: "Fluke Networks, part of Fortive Corporation (NYSE: FTV), makes the certification and troubleshooting tools that network installers depend on to verify structured cabling meets industry standards before a network goes live — a name considered essential across the cabling and installation industry.",
    website: "https://www.flukenetworks.com",
  },
  {
    name: "Ekahau",
    logo: `${B}/images/clientIcon/Ekahau.png`,
    category: "Network Infrastructure",
    tagline: "Wi-Fi Design & Validation",
    about: "Ekahau, based in Helsinki, Finland, has become the industry standard for Wi-Fi site surveys and wireless network planning. Network engineers worldwide rely on Ekahau's tools to visualize and validate wireless coverage before deployment, helping avoid costly connectivity blind spots in hospitals, warehouses, and large campuses.",
    website: "https://www.ekahau.com",
  },
  {
    name: "Hamina",
    logo: `/hamina.jpeg`,
    category: "Network Infrastructure",
    tagline: "Network Planning Solutions",
    about: "Hamina provides network planning and design tools that help engineers visualize and plan wireless and wired network deployments with precision. Their solutions are used by network professionals to streamline site planning and improve deployment accuracy.",
    website: "https://www.hamina.com",
  },
  {
    name: "NetAlly",
    logo: `${B}/images/clientIcon/netAlly.png`,
    category: "Network Infrastructure",
    tagline: "Handheld Network Testing",
    about: "NetAlly, spun off from NetScout Systems (NASDAQ: NTCT) in 2019 and based in Georgia, USA, builds handheld network testing tools that let IT technicians diagnose Wi-Fi and LAN issues on-site — fast, rugged, and built for field troubleshooting without needing a full laptop setup.",
    website: "https://www.netally.com",
  },

  // ─── Safety & Security ────────────────────────────────────────────────
  {
    name: "Axis Communications",
    logo: `${B}/images/clientIcon/Axis_logo.png`,
    category: "Safety & Security",
    tagline: "Network Video Surveillance",
    about: "Axis Communications, a subsidiary of Canon Inc. based in Lund, Sweden, pioneered network video surveillance and continues to lead in IP camera and video management technology — widely deployed across retail, transportation, and public safety applications that demand reliable, high-quality monitoring.",
    website: "https://www.axis.com",
  },
  {
    name: "Digifort",
    logo: `${B}/images/clientIcon/digifort_logo1.jpg`,
    category: "Safety & Security",
    tagline: "Video Management Software",
    about: "Digifort, a privately held Brazilian software company, develops video management software (VMS) that ties surveillance camera networks into a centralized, searchable monitoring platform — the software layer that makes hardware cameras genuinely usable.",
    website: "https://www.digifort.com.br",
  },
  {
    name: "Hanwha Vision",
    logo: `${B}/images/clientIcon/Hanwha%20Logo%20-%20160px%20x%2050px.png`,
    category: "Safety & Security",
    tagline: "CCTV & Surveillance Systems",
    about: "Hanwha Vision, part of South Korea's Hanwha Group and formerly known as Hanwha Techwin, manufactures CCTV cameras and surveillance systems used across commercial and industrial security deployments, offering a wide range of resolution and environmental durability options.",
    website: "https://www.hanwhavision.com",
  },
  {
    name: "GST",
    logo: `${B}/images/clientIcon/GSTimages.png`,
    category: "Safety & Security",
    tagline: "Fire Safety Systems",
    about: "GST specializes in fire detection and alarm system manufacturing, providing control panels and detection devices for commercial fire safety installations — trusted across a range of building types and fire safety standards.",
    website: "https://www.gst-support.com",
  },
  {
    name: "Honeywell",
    logo: `${B}/images/clientIcon/Honeywell%20-%20Freestanding%20Logo%20Red-EPS%20file.jpg`,
    category: "Safety & Security",
    tagline: "Safety & Building Technologies",
    about: "Honeywell, a Fortune 500 company (NASDAQ: HON), brings decades of expertise across safety, security, and building technologies. Its breadth of product lines makes it a common presence across multiple layers of a building's safety infrastructure, from fire detection to access control.",
    website: "https://www.honeywell.com",
  },
  {
    name: "Heinrich",
    logo: `${B}/images/clientIcon/Heinrich%20Logo%20-%20160px%20x%2050px.png`,
    category: "Safety & Security",
    tagline: "Security Solutions",
    about: "Heinrich provides security and safety solutions for enterprise environments. For the most accurate and current information about Heinrich's product portfolio and company background, we recommend consulting directly with PV Lumens or visiting the brand's official channels.",
    website: "https://www.pvlumens.com",
  },
  {
    name: "Morley-IAS",
    logo: `${B}/images/clientIcon/Morley_Logo.png`,
    category: "Safety & Security",
    tagline: "Fire Alarm Management",
    about: "Morley-IAS, part of Honeywell's fire safety portfolio, manufactures fire alarm control panels that serve as the central management unit for building fire detection networks.",
    website: "https://www.morleyias.com",
  },
  {
    name: "Texecom",
    logo: `${B}/images/clientIcon/TexecomLogo300pix.webp`,
    category: "Safety & Security",
    tagline: "Intruder Alarm Systems",
    about: "Texecom, a privately held UK security manufacturer, designs intruder alarm systems and control panels commonly installed by security integrators as part of layered building protection strategies.",
    website: "https://www.texe.com",
  },
  {
    name: "Notifier",
    logo: `${B}/images/clientIcon/Notifier%20Logo%20-%20160px%20x%2050px.png`,
    category: "Safety & Security",
    tagline: "Fire Alarm Control Panels",
    about: "Notifier, also part of Honeywell, is a well-established name in fire detection and alarm control panels, engineered to meet strict fire code compliance requirements across commercial and industrial installations.",
    website: "https://www.notifier.com",
  },
  {
    name: "Motorola Solutions",
    logo: `/motorola.webp`,
    category: "Safety & Security",
    tagline: "Public Safety & Enterprise Security",
    about: "Motorola Solutions is a major, long-established name in public safety and enterprise security technology — spanning communications, video security, and command center software used by government, enterprise, and public safety organizations globally. Publicly traded (NYSE: MSI), headquartered in Chicago, Illinois, USA.",
    website: "https://www.motorolasolutions.com",
  },
  {
    name: "Pelco",
    logo: `/pelco.png`,
    category: "Safety & Security",
    tagline: "Video Security Systems",
    about: "Pelco, a Motorola Solutions company, designs video security and surveillance systems, including cameras and video management software used across commercial and critical infrastructure security deployments. Acquired by Motorola Solutions in 2023; originally founded in California, USA.",
    website: "https://www.pelco.com",
  },
  {
    name: "Avigilon",
    logo: `/avilijon.jpeg`,
    category: "Safety & Security",
    tagline: "AI-Powered Video Security",
    about: "Avigilon, a Motorola Solutions company, specializes in AI-powered video security and access control systems, known for advanced video analytics capabilities in surveillance deployments. Acquired by Motorola Solutions in 2018; originally founded in Vancouver, Canada.",
    website: "https://www.avigilon.com",
  },
  {
    name: "Suprema",
    logo: `/suprema.jpeg`,
    category: "Safety & Security",
    tagline: "Biometric Access Control",
    about: "Suprema develops biometric authentication and access control systems, including fingerprint and facial recognition technology used in security and identity verification applications. South Korean company, publicly traded on the Korean stock exchange (KOSDAQ).",
    website: "https://www.supremainc.com",
  },
  {
    name: "ideaForge",
    logo: `${B}/images/clientIcon/ideaForgLogo.png`,
    category: "Safety & Security",
    tagline: "India's Largest Drone Manufacturer",
    about: "ideaForge, publicly traded on Indian stock exchanges (NSE/BSE: IDEAFORGE) since its 2023 IPO, is India's largest drone manufacturer by volume, producing UAVs for surveillance, mapping, and infrastructure inspection built around Indian regulatory and operational requirements.",
    website: "https://www.ideaforge.co.in",
  },
  {
    name: "75F",
    logo: `${B}/images/clientIcon/Logo%20-%2075F_3.png`,
    category: "Safety & Security",
    tagline: "Smart Building Automation",
    about: "75F provides IoT-based smart building automation solutions — sensors and controls that manage HVAC, lighting, and building systems for energy efficiency and automated building management. Privately held, headquartered in Minneapolis, Minnesota, USA.",
    website: "https://www.75f.io",
  },
  {
    name: "System Sensor",
    logo: `${B}/images/clientIcon/System_Sensor_logo.png`,
    category: "Safety & Security",
    tagline: "Fire Detection Devices",
    about: "System Sensor, a Honeywell subsidiary based in Illinois, manufactures the smoke detectors and fire notification devices that form the front-line detection layer of commercial fire alarm systems.",
    website: "https://www.systemsensor.com",
  },
  {
    name: "Checkpoint Systems",
    logo: `${B}/images/clientIcon/Checkpoint-Primary-Logo-Navy-2.png`,
    category: "Safety & Security",
    tagline: "Retail Loss Prevention & RFID",
    about: "Checkpoint Systems, part of CCL Industries (Toronto Stock Exchange: CCL) since 2018, provides retail loss prevention and RFID inventory solutions that bridge security and real-time stock visibility for retailers.",
    website: "https://www.checkpointsystems.com",
  },

  // ─── Business Productivity ────────────────────────────────────────────
  {
    name: "Zebra Technologies",
    logo: `${B}/images/clientIcon/Zebra.png`,
    category: "Business Productivity",
    tagline: "Barcode, RFID & Mobile Computing",
    about: "Zebra Technologies, a publicly traded company (NASDAQ: ZBRA) with roughly 10,000 employees globally, is a leading name in barcode scanners, mobile computers, RFID technology, and label printers — built to withstand demanding retail, warehousing, and logistics environments while enabling real-time data capture.",
    website: "https://www.zebra.com",
  },
  {
    name: "Honeywell Productivity",
    logo: `${B}/images/clientIcon/Honeywell%20-%20Freestanding%20Logo%20Red-EPS%20file.jpg`,
    category: "Business Productivity",
    tagline: "Enterprise Mobility Solutions",
    about: "Honeywell's productivity division delivers enterprise mobile computers, barcode scanners, and workflow solutions designed for warehousing, logistics, and field service environments — combining rugged hardware with Honeywell's software intelligence.",
    website: "https://sps.honeywell.com",
  },
  {
    name: "SUNMI",
    logo: `${B}/images/clientIcon/Sunmi%20Logo%20-%20160px%20x%2050px.png`,
    category: "Business Productivity",
    tagline: "Smart Android POS Terminals",
    about: "SUNMI, a privately held Chinese hardware company, designs smart Android-based POS terminals that combine hardware and software into ready-to-deploy commercial computing solutions for retailers and businesses.",
    website: "https://www.sunmi.com",
  },
  {
    name: "Ivanti Wavelink",
    logo: `${B}/images/clientIcon/ivanti-wavelink1.png`,
    category: "Business Productivity",
    tagline: "Mobile Computing for Warehouses",
    about: "Ivanti Wavelink, part of Ivanti's enterprise software portfolio, provides the mobile computing software that connects and manages rugged devices used across warehouses and industrial environments. Its terminal emulation technology allows modern hardware to run legacy warehouse management systems.",
    website: "https://www.ivanti.com/wavelink",
  },
  // ─── Test & Measurement ───────────────────────────────────────────────
  {
    name: "Megger",
    logo: `${B}/images/clientIcon/Megger.png`,
    category: "Test & Measurement",
    tagline: "Electrical Testing Equipment",
    about: "Megger, headquartered in Dover, England, brings over 130 years of expertise to electrical testing equipment, particularly insulation resistance testers and cable fault locators. Electricians and utility engineers rely on Megger's instruments to catch electrical faults before they become safety hazards or costly failures.",
    website: "https://www.megger.com",
  },
  {
    name: "Teledyne FLIR",
    logo: `${B}/images/clientIcon/TeledyneFLIR2.png`,
    category: "Test & Measurement",
    tagline: "Thermal Imaging Technology",
    about: "Teledyne FLIR, part of Teledyne Technologies (NYSE: TDY), is the name synonymous with thermal imaging technology. Its cameras detect heat patterns invisible to the naked eye, helping identify electrical faults, insulation gaps, and equipment overheating across industrial inspection and security applications.",
    website: "https://www.teledyneflir.com",
  },
  {
    name: "Extech",
    logo: `/extech.jpeg`,
    category: "Test & Measurement",
    tagline: "Test & Measurement Instruments",
    about: "Extech, a FLIR company, manufactures test and measurement instruments — multimeters, environmental meters, and thermal imaging tools aimed at trade and industrial testing applications. Acquired by FLIR Systems (now Teledyne FLIR) in 2007; originally founded in Massachusetts, USA.",
    website: "https://www.extech.com",
  },
  {
    name: "Fluke",
    logo: `${B}/images/clientIcon/FNet_White_Blue_Box_RGB.JPG`,
    category: "Test & Measurement",
    tagline: "Portable Test & Measurement Tools",
    about: "Fluke is one of the most recognized names in portable test and measurement instruments — multimeters, clamp meters, and diagnostic tools used across electrical, industrial, and maintenance applications worldwide. Part of Fortive Corporation (NYSE: FTV). Note: Fluke and Fluke Networks are related but operate as separate product lines under the same parent company.",
    website: "https://www.fluke.com",
  },
  {
    name: "Testo",
    logo: `${B}/images/clientIcon/TESTO-img.jpg`,
    category: "Test & Measurement",
    tagline: "Precision Measurement Instruments",
    about: "Testo, a privately held, family-owned German company based in Titisee-Neustadt, has specialized in precision measurement instruments since 1957. Its handheld devices for temperature, humidity, and emissions testing are trusted across industrial, HVAC, and food safety applications where accuracy directly affects compliance and safety.",
    website: "https://www.testo.com",
  },
];

export const CATEGORIES = Array.from(new Set(BRAND_DATA.map(b => b.category)));
